String Transforms
===============================

## Reverser
```{r}
reverser <- function(word){
  letters <- (strsplit(word,""))
  x<- rev(letters[[1]])
  paste(x,collapse="")
}
```

```{r}
# Test Statements
reverser("computer")
reverser("cat")
```

## Scrambler
```{r}
Scrambler <- function(word){
  letters <- (strsplit(word,""))
  x<- sample(letters[[1]])
  paste(x,collapse="")
}
```

```{r}
# Test Statements
Scrambler("hello")
```

## VowelBleeper
```{r}
# Definition Here
VowelBleeper <- function(word){
 gsub("[aeiouAEIOU]","*", word)
  }
```

```{r}
# Test Statements
VowelBleeper("computer")
VowelBleeper("higher")
VowelBleeper("cat")
VowelBleeper("Art")
```

## L33t 
```{r}
L33t <- function(word){
  one <- gsub("[Ee]","3", word)
  two <- gsub( "[Oo]", "0", one)
  three <- gsub("[Aa]", "4", two)
  four <- gsub("[Ll]", "1", three)
  five <- gsub("[Gg]", "9", four)
  gsub("[Ss]", "5", five)
  }
```

```{r}
# Test Statements
L33t("People at Macalester are awesome")
L33t("Larry likes lemons")
```

## Sets of Words
```{r}
# Reverser
Reverser <- function(word){
reverser <- function(word){
  letters <- (strsplit(word,""))
  x <- rev(letters[[1]])
  paste(x,collapse="")
  }
sapply(word,reverser)
}
```

```{r}
# Test Statements
Reverser(c("dog", "cat"))
```

```{r}
# Scrambler
scrambler <- function(word){
Scrambler <- function(word){
  letters <- (strsplit(word,""))
  x<- sample(letters[[1]])
  paste(x,collapse="")
}
sapply(word,Scrambler)
}
```

```{r}
# Test Statements
scrambler(c("hello","cowboy"))
```

```{r}
# VowelBleeper
vowelbleeper <- function(word){
VowelBleeper <- function(word){
 gsub("[aeiouAEIOU]","*", word)
  }
  sapply(word,VowelBleeper)
  }
```

```{r}
# Test Statements
vowelbleeper(c("elephant","cartoon"))
```

```{r}
# L33t
Leet <- function(word){
L33t <- function(word){
  one <- gsub("[Ee]","3", word)
  two <- gsub( "[Oo]", "0", one)
  three <- gsub("[Aa]", "4", two)
  four <- gsub("[Ll]", "1", three)
  five <- gsub("[Gg]", "9", four)
  gsub("[Ss]", "5", five)
  }
sapply(word,L33t)
}
```

```{r}
# Test Statements
Leet(c("submarine", "elephant"))
```


