Recursion Intro
========================================================

# Write another form of the loop
```{r}


```

# Add NSeq 
```{r}
addNSeq <- function(v){
  sum <- 0 # accumulator
  for(k in 1:length(v)) {
    sum <- sum + v[k]
    }
  return(sum)
  }
```

# Test Cases
```{r}
addNSeq(1:10)
```

# Adding Recursively
```{r}
newAddNSeq <- function(v){
  # Base Case
  if (length(v)==0) return(0)
  return(v[1] + newAddNSeq(v[-1]))
}
```

# Test Cases
```{r}
newAddNSeq(1:10)
```

# Natural settings for recursion
```{r}
integrateRecursive <- function(f, a = 0, b = 1) {
    bigBins <- simpleRiemann(f, a = a, b = b, n = 5)
    smallBins <- simpleRiemann(f, a = a, b = b, n = 10)
    if (abs(bigBins - smallBins) < 1e-05) 
        return(smallBins) else {
        mid <- (a + b)/2
        total <- integrateRecursive(f, a = a, b = mid) + integrateRecursive(f, 
            a = mid, b = b)
        return(total)
    }
}
```


# Plotting a function
```{r}
plotF <- function(f, a=0, b=1){
  # State 
  
  # Loop
  
  # Change
  
  # Return
  return()
  
```

# gaussQuadrature function thing
```{r}
gaussQuadrature <- function(f, a = 0, b = 1) {
    # Just 4 function evaluations!

    # 'Magic' values on z in [0,1]
    z <- c(c(-1, 1) * sqrt((3 - 2 * sqrt(6/5))/7), c(-1, 1) * sqrt((3 + 2 * 
        sqrt(6/5))/7))
    # weights (analogous to bin width)
    w <- c(rep((18 + sqrt(30))/36, 2), rep((18 - sqrt(30))/36, 2))
    # Translate to interval x in [a,b]
    x <- ((b - a)/2) * z + (a + b)/2
    # evaluate the function at x, multiply by weights, and sum
    return(((b - a)/2) * sum(w * sapply(x, f)))
}
```


# getX function
```{r}
getX <- function(f, a=0, b=1){
  # state
  
  # loop
  
  # change state
  
  # return
  return()
  
```


