# Functions and Graphics
========================================================

# countOdds function
```{r}
countOdds <- function(x){
  
  return()
  }
```
 
## Test Cases
```{r}
countOdds(1:9)
```

```{r}
countOdds(c(3,5,7))
```

```{r}
countOdds(c(3,5,7,6,2,0))
```

# countEvens function
```{r}
countEvens <- function (x){
  
  }
```

## Test Cases
```{r}
countEvens(1:9)
```

```{r}
countEvens(c(3,5,7))
```

```{r}
countEvens(c(3,5,7,6,2,0))
```

# Triangles
## hypotenuseLength function
```{r}
hypotenuseLength <- function(a,b){
  
}
```

## Test Cases
```{r}
hypotenuseLength(3,4)
```

```{r}
hypotenuseLength(13,84)
```

# lawOfCosines function
```{r}
lawOfCosines <- function(a,b,theta){
  
  return(c)
  }
```

## Test Cases
```{r}
lawOfCosines(13,84,pi/2) # right triangle
```

```{r}
lawOfCosines(13,84,0) # collapsed with theta=0
```

```{r}
lawOfCosines(5,5,pi/3)
```

# thetaFromLengths function
```{r}
thetaFromLengths <- function(a,b,c){
  
  return(theta)
  }
```

## Test Case
```{r}
thetaFromLengths(3,4,5) # should be pi/2
```

# thetaFromLengthsTest function
```{r}
thetaFromLengthsTest <- function(a,b,theta){
  
  return()
  }
```

# Graphics
## canvas funtion
```{r}

```

## drawCircle function
```{r}

```
 


