Final Exam
========================================================

```{r}
require(mosaic)
fetchData("COMP121/word-hints.R")
```

# letterProportion function
```{r}
letterProportion <- function(string){
  small <- strsplit(string, split = "") # split up the character string into individual letters
  tolower(small) #Put character sting in all lowercase
  table(small) # make a table of those letters from the character string. Need to make the result a proportion.

  }
```


# FreqCompare function
```{r}
E <- English #Define the languages(Probably not needed?)
G <- German
Fi <- Finnish
Fr <- French
I <- Italian
S <- Spanish
freqCompare <- function(output from letterProportion, language) #Output will be a table and choose a language{
  observed <- small "letter frequency from the string" #letter proportion from the character string
  languageFreq <- "language frequency" #letter proportion from the language chosen(either English,Spanish,German,Finnish,French,Italian)
  difference <- (observed - languageFreq)
  chisq <- ((difference^2)%%languageFreq) #Chisq test
  
  }
```

# WhichLanguage function
```{r}
whichLanguage <- function(character string as a language, list(English,German,Finnish,French,Italian,Spanish)){
  EnglDiff <- (English - Chisq)
  GermDiff <- (German - Chisq)
  FinnDiff <- (Finnish - Chisq)
  FrenDiff <- (French - Chisq)
  ItalDiff <- (Italian - Chisq)
  SpanDiff <- (Spanish - Chisq)
  which.min(EnglDiff,GermDiff,FinnDiff,FrenDiff,ItalDiff,SpanDiff)
  
  return(which.min) #language with smallest chisq
  }
```




