## Numbers and Strings
========================================================

## Outlier function
```{r}
outlier <- function(x){
 # State
  x <- c(0:9)
  
# Update state
  outlier <- quantile(x, probs = seq(0,.25,.75), na.rm = FALSE, names = TRUE)
  
  
  v <- quantile(x)
  one <- v[[2]]
  two <- v[[4]]
  for (k in 0:length(x)){
    if (one<x[k])
      return(TRUE)
    if (x[k]<two)
      return(TRUE)
    }
  else (return(FALSE))
  }
```
## Test Case
```{r}
outlier()
```
## Digit to Word function
```{r}
digitToWord <- function(x, y){
  
  }
```

## LettersMatch function
```{r}
LettersMatch <- function(words,pattern){
  small <- c("first", "second","errand","arrest","are")
  match <- grepl("^...$",small) # three letters long
  return(match)
  }
```

## Test Case
```{r}
LettersMatch()
```
## piSeries function
```{r}
piSeries <- function(n){
  
  }
```

## How Close to Pi function
```{r}
howCloseToPi <- function(n){

  }
```

## Random Approx. to Pi function
```{r}
randomApproxToPi <- function(n){

  }
```



